### ISSUE TITLE
ECONNRESET and ECONNREFUSED

### ISSUE THREAD

**Issue by willcosgrove** [codota/tabnine-atom#21]
I get these errors frequently, probably every 5-10 minutes or so.  The autocompleting doesn't appear to break, but the error messages are annoying.  If it is part of normal operation, then the Atom plugin should be catching the error.  I suspect it isn't part of normal operation, so I decided to raise this issue in the main TabNine repo.

I've attached a video of the error, as I don't get any output in the developer console of Atom, and the error messages go away very quickly.

[Screen Capture 3-27-20, 5.02.44 PM.mp4.zip](https://github.com/codota/TabNine/files/4396136/Screen.Capture.3-27-20.5.02.44.PM.mp4.zip)

And here's a gif of the video for convenience.  The video download link above has better resolution.
![Screen Capture 3-27-20, 5 02 44 PM](https://user-images.githubusercontent.com/77887/77804921-af5ba400-704e-11ea-9afb-8f2dcba6d6cb.gif)

**Comment by dimacodota** [comment]
hi @willcosgrove, 
could you please open the dev tools (View -> Developer -> Toggle Developer Tools) and attach the stack trace logs?

**Comment by seveibar** [comment]
when I got this error, there weren't any logs in my console (which I had open)

**Comment by dimacodota** [comment]
the fix will be released in the upcoming TabNine binary release

**Comment by dimacodota** [comment]
the fix is available in TabNine beta version

you can try it by enabling the beta version:

type TabNine::config and check the "Receive beta releases of TabNine" option

**Comment by Jmulder08** [comment]
I enabled the beta release, but I still get the ECONNREFUSED error every time I open atom.
